# Generated by Django 3.1.6 on 2021-03-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_book_control', '0002_auto_20210228_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
